# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(904, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 891, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.label_filters_input = QtWidgets.QLabel(self.tab_filters)
        self.label_filters_input.setGeometry(QtCore.QRect(180, 30, 331, 231))
        self.label_filters_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_input.setObjectName("label_filters_input")
        self.label_filters_output = QtWidgets.QLabel(self.tab_filters)
        self.label_filters_output.setGeometry(QtCore.QRect(520, 30, 331, 231))
        self.label_filters_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_output.setTextFormat(QtCore.Qt.PlainText)
        self.label_filters_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_output.setObjectName("label_filters_output")
        self.pushButton_filters_load = QtWidgets.QPushButton(self.tab_filters)
        self.pushButton_filters_load.setGeometry(QtCore.QRect(20, 30, 121, 81))
        self.pushButton_filters_load.setObjectName("pushButton_filters_load")
        self.label = QtWidgets.QLabel(self.tab_filters)
        self.label.setGeometry(QtCore.QRect(30, 140, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_filters)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 71, 21))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_filters)
        self.groupBox.setGeometry(QtCore.QRect(30, 280, 751, 111))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.tabWidget.addTab(self.tab_filters, "")
        self.tab_lines = QtWidgets.QWidget()
        self.tab_lines.setObjectName("tab_lines")
        self.label_lines_input = QtWidgets.QLabel(self.tab_lines)
        self.label_lines_input.setGeometry(QtCore.QRect(150, 30, 241, 171))
        self.label_lines_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_lines_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_lines_input.setObjectName("label_lines_input")
        self.label_4 = QtWidgets.QLabel(self.tab_lines)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_lines)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 71, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton_lines_load = QtWidgets.QPushButton(self.tab_lines)
        self.pushButton_lines_load.setGeometry(QtCore.QRect(20, 30, 121, 81))
        self.pushButton_lines_load.setObjectName("pushButton_lines_load")
        self.label_lines_hough = QtWidgets.QLabel(self.tab_lines)
        self.label_lines_hough.setGeometry(QtCore.QRect(150, 210, 561, 191))
        self.label_lines_hough.setFrameShape(QtWidgets.QFrame.Box)
        self.label_lines_hough.setTextFormat(QtCore.Qt.PlainText)
        self.label_lines_hough.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_lines_hough.setObjectName("label_lines_hough")
        self.label_lines_input_2 = QtWidgets.QLabel(self.tab_lines)
        self.label_lines_input_2.setGeometry(QtCore.QRect(450, 30, 261, 171))
        self.label_lines_input_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_lines_input_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_lines_input_2.setObjectName("label_lines_input_2")
        self.tabWidget.addTab(self.tab_lines, "")
        self.tab_circles = QtWidgets.QWidget()
        self.tab_circles.setEnabled(True)
        self.tab_circles.setObjectName("tab_circles")
        self.pushButton_circles_load = QtWidgets.QPushButton(self.tab_circles)
        self.pushButton_circles_load.setGeometry(QtCore.QRect(50, 30, 121, 81))
        self.pushButton_circles_load.setObjectName("pushButton_circles_load")
        self.label_circles_input = QtWidgets.QLabel(self.tab_circles)
        self.label_circles_input.setGeometry(QtCore.QRect(180, 30, 241, 171))
        self.label_circles_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_circles_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_circles_input.setObjectName("label_circles_input")
        self.label_circles_hough = QtWidgets.QLabel(self.tab_circles)
        self.label_circles_hough.setGeometry(QtCore.QRect(180, 210, 561, 191))
        self.label_circles_hough.setFrameShape(QtWidgets.QFrame.Box)
        self.label_circles_hough.setTextFormat(QtCore.Qt.PlainText)
        self.label_circles_hough.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_circles_hough.setObjectName("label_circles_hough")
        self.label_6 = QtWidgets.QLabel(self.tab_circles)
        self.label_6.setGeometry(QtCore.QRect(60, 140, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_circles)
        self.label_7.setGeometry(QtCore.QRect(60, 170, 71, 21))
        self.label_7.setObjectName("label_7")
        self.label_circles_output = QtWidgets.QLabel(self.tab_circles)
        self.label_circles_output.setGeometry(QtCore.QRect(480, 30, 261, 171))
        self.label_circles_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_circles_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_circles_output.setObjectName("label_circles_output")
        self.tabWidget.addTab(self.tab_circles, "")
        self.tab_corners = QtWidgets.QWidget()
        self.tab_corners.setObjectName("tab_corners")
        self.pushButton_corners_load = QtWidgets.QPushButton(self.tab_corners)
        self.pushButton_corners_load.setGeometry(QtCore.QRect(30, 30, 121, 81))
        self.pushButton_corners_load.setObjectName("pushButton_corners_load")
        self.label_corners_input = QtWidgets.QLabel(self.tab_corners)
        self.label_corners_input.setGeometry(QtCore.QRect(260, 10, 401, 191))
        self.label_corners_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_corners_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_corners_input.setObjectName("label_corners_input")
        self.label_8 = QtWidgets.QLabel(self.tab_corners)
        self.label_8.setGeometry(QtCore.QRect(40, 140, 71, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_corners)
        self.label_9.setGeometry(QtCore.QRect(40, 170, 71, 21))
        self.label_9.setObjectName("label_9")
        self.label_corners_corners_output = QtWidgets.QLabel(self.tab_corners)
        self.label_corners_corners_output.setGeometry(QtCore.QRect(260, 210, 401, 201))
        self.label_corners_corners_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_corners_corners_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_corners_corners_output.setObjectName("label_corners_corners_output")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_corners)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 210, 201, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.label_15.setObjectName("label_15")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(70, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 50, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 80, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 110, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.tabWidget.addTab(self.tab_corners, "")
        self.tab_histograms = QtWidgets.QWidget()
        self.tab_histograms.setObjectName("tab_histograms")
        self.label_histograms_houtput = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_houtput.setGeometry(QtCore.QRect(520, 200, 261, 191))
        self.label_histograms_houtput.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_houtput.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_houtput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_houtput.setObjectName("label_histograms_houtput")
        self.pushButton_histograms_load = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_histograms_load.setGeometry(QtCore.QRect(40, 20, 121, 81))
        self.pushButton_histograms_load.setObjectName("pushButton_histograms_load")
        self.label_histograms_input = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_input.setGeometry(QtCore.QRect(270, 20, 241, 171))
        self.label_histograms_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input.setObjectName("label_histograms_input")
        self.label_histograms_output = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_output.setGeometry(QtCore.QRect(520, 20, 261, 171))
        self.label_histograms_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output.setObjectName("label_histograms_output")
        self.label_10 = QtWidgets.QLabel(self.tab_histograms)
        self.label_10.setGeometry(QtCore.QRect(50, 160, 71, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_histograms)
        self.label_11.setGeometry(QtCore.QRect(50, 130, 71, 21))
        self.label_11.setObjectName("label_11")
        self.label_histograms_hinput = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_hinput.setGeometry(QtCore.QRect(270, 200, 241, 191))
        self.label_histograms_hinput.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput.setObjectName("label_histograms_hinput")
        self.radioButton = QtWidgets.QRadioButton(self.tab_histograms)
        self.radioButton.setGeometry(QtCore.QRect(20, 220, 112, 23))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_histograms)
        self.radioButton_2.setGeometry(QtCore.QRect(130, 220, 112, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_histograms_load_target = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_histograms_load_target.setGeometry(QtCore.QRect(30, 280, 161, 71))
        self.pushButton_histograms_load_target.setObjectName("pushButton_histograms_load_target")
        self.tabWidget.addTab(self.tab_histograms, "")
        self.tab_face_detection = QtWidgets.QWidget()
        self.tab_face_detection.setObjectName("tab_face_detection")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_face_detection)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 320, 751, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 311, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(380, 10, 311, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(30, 20, 111, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(30, 40, 101, 20))
        self.label_24.setObjectName("label_24")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_11.setGeometry(QtCore.QRect(170, 20, 113, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_12.setGeometry(QtCore.QRect(170, 40, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        self.label_27.setGeometry(QtCore.QRect(30, 60, 101, 20))
        self.label_27.setObjectName("label_27")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_13.setGeometry(QtCore.QRect(170, 60, 113, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_segmentation_input_2 = QtWidgets.QLabel(self.tab_face_detection)
        self.label_segmentation_input_2.setGeometry(QtCore.QRect(190, 30, 331, 231))
        self.label_segmentation_input_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_segmentation_input_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_segmentation_input_2.setObjectName("label_segmentation_input_2")
        self.label_segmentation_output_2 = QtWidgets.QLabel(self.tab_face_detection)
        self.label_segmentation_output_2.setGeometry(QtCore.QRect(530, 30, 331, 231))
        self.label_segmentation_output_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_segmentation_output_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_segmentation_output_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_segmentation_output_2.setObjectName("label_segmentation_output_2")
        self.label_25 = QtWidgets.QLabel(self.tab_face_detection)
        self.label_25.setGeometry(QtCore.QRect(40, 170, 71, 21))
        self.label_25.setObjectName("label_25")
        self.pushButton_segment_load_2 = QtWidgets.QPushButton(self.tab_face_detection)
        self.pushButton_segment_load_2.setGeometry(QtCore.QRect(30, 30, 121, 81))
        self.pushButton_segment_load_2.setObjectName("pushButton_segment_load_2")
        self.label_26 = QtWidgets.QLabel(self.tab_face_detection)
        self.label_26.setGeometry(QtCore.QRect(40, 140, 71, 21))
        self.label_26.setObjectName("label_26")
        self.pushButton_segment = QtWidgets.QPushButton(self.tab_face_detection)
        self.pushButton_segment.setGeometry(QtCore.QRect(790, 340, 81, 61))
        self.pushButton_segment.setObjectName("pushButton_segment")
        self.tabWidget.addTab(self.tab_face_detection, "")
        self.tab_SIFT = QtWidgets.QWidget()
        self.tab_SIFT.setObjectName("tab_SIFT")
        self.label_snake = QtWidgets.QLabel(self.tab_SIFT)
        self.label_snake.setGeometry(QtCore.QRect(220, 20, 401, 291))
        self.label_snake.setFrameShape(QtWidgets.QFrame.Box)
        self.label_snake.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_snake.setObjectName("label_snake")
        self.pushButton_snake_load = QtWidgets.QPushButton(self.tab_SIFT)
        self.pushButton_snake_load.setGeometry(QtCore.QRect(20, 20, 121, 81))
        self.pushButton_snake_load.setObjectName("pushButton_snake_load")
        self.pushButton_snake_start = QtWidgets.QPushButton(self.tab_SIFT)
        self.pushButton_snake_start.setGeometry(QtCore.QRect(20, 110, 121, 81))
        self.pushButton_snake_start.setObjectName("pushButton_snake_start")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_SIFT)
        self.groupBox_4.setGeometry(QtCore.QRect(220, 320, 401, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(140, 20, 47, 13))
        self.label_19.setObjectName("label_19")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(50, 20, 71, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(170, 20, 71, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(250, 20, 47, 13))
        self.label_20.setObjectName("label_20")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(300, 20, 71, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.tabWidget.addTab(self.tab_SIFT, "")
        self.tab_segmentation = QtWidgets.QWidget()
        self.tab_segmentation.setObjectName("tab_segmentation")
        self.tabWidget.addTab(self.tab_segmentation, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.tabWidget.addTab(self.widget, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 904, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_filters_input.setText(_translate("MainWindow", "Input image"))
        self.label_filters_output.setText(_translate("MainWindow", "Output image"))
        self.pushButton_filters_load.setText(_translate("MainWindow", "Load Image"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Size:"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter Setting"))
        self.label_3.setText(_translate("MainWindow", "Select Filter"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Box Filter"))
        self.comboBox.setItemText(1, _translate("MainWindow", "LPF"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Sharpening Filter"))
        self.comboBox.setItemText(3, _translate("MainWindow", "LOG"))
        self.comboBox.setItemText(4, _translate("MainWindow", "DOG"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Gaussian Filter"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Median Filter"))
        self.comboBox.setItemText(7, _translate("MainWindow", "HPF"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Sobel edge detection"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Fourier Transform"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_filters), _translate("MainWindow", "Filters"))
        self.label_lines_input.setText(_translate("MainWindow", "Input image"))
        self.label_4.setText(_translate("MainWindow", "Name:"))
        self.label_5.setText(_translate("MainWindow", "Size:"))
        self.pushButton_lines_load.setText(_translate("MainWindow", "Load Image"))
        self.label_lines_hough.setText(_translate("MainWindow", "Hough Space"))
        self.label_lines_input_2.setText(_translate("MainWindow", "Image with significant lines"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lines), _translate("MainWindow", "Lines"))
        self.pushButton_circles_load.setText(_translate("MainWindow", "Load Image"))
        self.label_circles_input.setText(_translate("MainWindow", "Input image"))
        self.label_circles_hough.setText(_translate("MainWindow", "Hough Space"))
        self.label_6.setText(_translate("MainWindow", "Name:"))
        self.label_7.setText(_translate("MainWindow", "Size:"))
        self.label_circles_output.setText(_translate("MainWindow", "Image with significant lines"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_circles), _translate("MainWindow", "Circles"))
        self.pushButton_corners_load.setText(_translate("MainWindow", "Load Image"))
        self.label_corners_input.setText(_translate("MainWindow", "Input Image"))
        self.label_8.setText(_translate("MainWindow", "Name:"))
        self.label_9.setText(_translate("MainWindow", "Size:"))
        self.label_corners_corners_output.setText(_translate("MainWindow", "Corner Image"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Additional Parameters"))
        self.label_12.setText(_translate("MainWindow", "Window: "))
        self.label_13.setText(_translate("MainWindow", "Std:"))
        self.label_14.setText(_translate("MainWindow", "K:"))
        self.label_15.setText(_translate("MainWindow", "Ratio: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_corners), _translate("MainWindow", "Corners"))
        self.label_histograms_houtput.setText(_translate("MainWindow", "Output Histogram"))
        self.pushButton_histograms_load.setText(_translate("MainWindow", "Load image"))
        self.label_histograms_input.setText(_translate("MainWindow", "Input image"))
        self.label_histograms_output.setText(_translate("MainWindow", "Output image"))
        self.label_10.setText(_translate("MainWindow", "Size:"))
        self.label_11.setText(_translate("MainWindow", "Name:"))
        self.label_histograms_hinput.setText(_translate("MainWindow", "Input Histogram"))
        self.radioButton.setText(_translate("MainWindow", "Equalization"))
        self.radioButton_2.setText(_translate("MainWindow", "Matching"))
        self.pushButton_histograms_load_target.setText(_translate("MainWindow", "Load target image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_histograms), _translate("MainWindow", "Histograms"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Segmentation Setting"))
        self.label_22.setText(_translate("MainWindow", "Select segmentation method"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Kmeans"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Mean Shift"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Region Growing"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Additional Parameters"))
        self.label_23.setText(_translate("MainWindow", "# of Clusters (k)"))
        self.label_24.setText(_translate("MainWindow", "# of Iterations"))
        self.label_27.setText(_translate("MainWindow", "Dim of Feature space"))
        self.label_segmentation_input_2.setText(_translate("MainWindow", "Input image"))
        self.label_segmentation_output_2.setText(_translate("MainWindow", "Output image"))
        self.label_25.setText(_translate("MainWindow", "Size:"))
        self.pushButton_segment_load_2.setText(_translate("MainWindow", "Load Image"))
        self.label_26.setText(_translate("MainWindow", "Name:"))
        self.pushButton_segment.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_face_detection), _translate("MainWindow", "Clustering/Segmentation"))
        self.label_snake.setText(_translate("MainWindow", "Input image"))
        self.pushButton_snake_load.setText(_translate("MainWindow", "Load Image"))
        self.pushButton_snake_start.setText(_translate("MainWindow", "Start"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Additional Parameters"))
        self.label_18.setText(_translate("MainWindow", "alpha"))
        self.label_19.setText(_translate("MainWindow", "Beta"))
        self.label_20.setText(_translate("MainWindow", "Gamma"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SIFT), _translate("MainWindow", "Snake"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

